dist: trusty
sudo: required
language: cpp
compiler: clang

before_script:
 - sudo apt-get install libboost-test-dev -y
 - sudo apt-get update -qq
 - sudo apt-get intall doxygen
 - sudo apt-get intall graphviz
script:
 - cmake .
 - cmake --build .
 - cmake --build . --target test
 - cmake --build . --target package
 - doxygen
deploy:
 - provider: script
   skip_cleanup: true
   script:
   - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ulex-96:$BINTRAY_API_KEY "https://api.bintray.com/content/lex-96/hw/hw4/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER_Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
 - provider: pages
   skip-cleanup: true
   github-token: $GITHUB_TOKEN
   keep-history: true
   local_dir: html
   on:
    branch: master

